In [1]:
import numpy as np

In [2]:
np.random.seed(0)
A=np.random.randint(0,10,[2,3])
B=np.ones((2,3))
A

array([[5, 0, 3],
       [3, 7, 9]])

In [3]:
B

array([[1., 1., 1.],
       [1., 1., 1.]])

In [4]:
A+B

array([[ 6.,  1.,  4.],
       [ 4.,  8., 10.]])